weights: yolov7-e6e.pt
cfg: cfg/training/yolov7-e6e.yaml
data: chestxray.yaml
hyp: data/hyp.scratch.p6.yaml
epochs: 200
batch_size: 8
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 2
project: DoQuocDang_STEAM
entity: null
name: yolov7_e6e_chest_xray_new
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
v5_metric: false
world_size: 1
global_rank: -1
save_dir: DoQuocDang_STEAM/yolov7_e6e_chest_xray_new3
total_batch_size: 8
